version: '2'

services:
  django:
    build: .
    container_name: muscatalog
    restart: always
    volumes:
      - static:/muscatalog/static
    ports:
      - '8001:8001'
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - static:/static
    ports:
      - '80:80'
    depends_on:
      - django
volumes:
  static:
